FROM node:20-alpine AS builder

WORKDIR /app
COPY apps/data-management-frontend/package.json apps/data-management-frontend/package-lock.json ./
RUN npm ci
COPY apps/data-management-frontend .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 4173
CMD ["serve", "-s", "dist", "-l", "4173"]
