"""Shared configuration loading, env var parsing, and service endpoint resolution."""

from vecinita_config.config import (
    ADMIN_TOKEN,
    BASE_DIR,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    CORPUS_DB_VALIDATION,
    DATABASE_URL,
    DB_DATA_MODE,
    DEFAULT_PROVIDER,
    EMBEDDING_DIMENSION,
    EMBEDDING_MODEL,
    EMBEDDING_SERVICE_URL,
    GUARDRAILS_ENABLED,
    GUARDRAILS_HALLUCINATION,
    GUARDRAILS_PII,
    GUARDRAILS_PROMPT_INJECTION,
    GUARDRAILS_TOPIC_LIST,
    GUARDRAILS_TOPIC_RELEVANCE,
    GUARDRAILS_TOXICITY,
    MAX_UPLOAD_SIZE_MB,
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    _normalize_internal_service_url,
    _running_on_render,
    _truthy_env,
    normalize_agent_service_url,
    postgres_data_reads_enabled,
    resolve_data_db_mode,
    rewrite_deprecated_modal_embedding_host,
)
from vecinita_config.service_endpoints import (
    AGENT_SERVICE_URL,
    EMBEDDING_ENDPOINT,
    MODEL_ENDPOINT,
    SCRAPER_ENDPOINT,
    get_allowed_origins,
    is_render,
    is_render_strict_mode,
    log_endpoint_summary,
)

__all__ = [
    # config.py — constants
    "ADMIN_TOKEN",
    "BASE_DIR",
    "CHUNK_OVERLAP",
    "CHUNK_SIZE",
    "CORPUS_DB_VALIDATION",
    "DATABASE_URL",
    "DB_DATA_MODE",
    "DEFAULT_PROVIDER",
    "EMBEDDING_DIMENSION",
    "EMBEDDING_MODEL",
    "EMBEDDING_SERVICE_URL",
    "GUARDRAILS_ENABLED",
    "GUARDRAILS_HALLUCINATION",
    "GUARDRAILS_PII",
    "GUARDRAILS_PROMPT_INJECTION",
    "GUARDRAILS_TOPIC_LIST",
    "GUARDRAILS_TOPIC_RELEVANCE",
    "GUARDRAILS_TOXICITY",
    "MAX_UPLOAD_SIZE_MB",
    "OLLAMA_BASE_URL",
    "OLLAMA_MODEL",
    # config.py — functions
    "_normalize_internal_service_url",
    "_running_on_render",
    "_truthy_env",
    "normalize_agent_service_url",
    "postgres_data_reads_enabled",
    "resolve_data_db_mode",
    "rewrite_deprecated_modal_embedding_host",
    # service_endpoints.py — constants
    "AGENT_SERVICE_URL",
    "EMBEDDING_ENDPOINT",
    "MODEL_ENDPOINT",
    "SCRAPER_ENDPOINT",
    # service_endpoints.py — functions
    "get_allowed_origins",
    "is_render",
    "is_render_strict_mode",
    "log_endpoint_summary",
]
