/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service index
         * @description Public landing; job routes still need ``Authorization: Bearer``.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description List recent scraping jobs (limited to last 50).
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /**
         * Submit a new scraping job
         * @description Persists the job and starts crawl work via Modal ``Function.spawn`` on ``scraper_worker`` when possible (returns ``modal_function_call_id``); otherwise enqueues to the ``scrape-jobs`` Modal queue. Downstream pipeline stages still use Modal queues and drains.
         */
        post: operations["submit_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/spawns/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Modal scrape worker spawn result
         * @description Wraps Modal ``FunctionCall.from_id(call_id)`` and ``get(timeout=0)`` (non-blocking poll), matching Modal's FastAPI job-queue example: 202 while running, 404 when expired/missing, 200 with JSON when the ``scraper_worker`` invocation finished.
         */
        get: operations["poll_scrape_spawn_result_jobs_spawns__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job status
         * @description Retrieve the current status and progress of a scraping job.
         */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a job
         * @description Cancel a scraping job if it hasn't completed.
         */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChunkingConfig
         * @description Semantic chunking parameters applied after Docling extraction.
         */
        ChunkingConfig: {
            /**
             * Max Size Tokens
             * @description Hard maximum chunk size in tokenizer tokens.
             * @default 1024
             * @example 1024
             */
            max_size_tokens: number;
            /**
             * Min Size Tokens
             * @description Soft minimum chunk size in tokenizer tokens.
             * @default 256
             * @example 256
             */
            min_size_tokens: number;
            /**
             * Overlap Ratio
             * @description Fraction of overlap between adjacent chunks.
             * @default 0.2
             * @example 0.2
             */
            overlap_ratio: number;
            /**
             * Split By Sentence
             * @description Prefer sentence boundaries when splitting.
             * @default true
             * @example true
             */
            split_by_sentence: boolean;
        };
        /**
         * CrawlConfig
         * @description Tuning knobs for the Crawl4AI crawl stage.
         */
        CrawlConfig: {
            /**
             * Headless
             * @description Run the browser headless.
             * @default true
             * @example true
             */
            headless: boolean;
            /**
             * Include Images
             * @description Whether to download image assets (higher bandwidth).
             * @default false
             * @example false
             */
            include_images: boolean;
            /**
             * Include Links
             * @description Whether discovered links are enqueued for deeper crawling.
             * @default true
             * @example true
             */
            include_links: boolean;
            /**
             * Max Depth
             * @description Maximum link depth to follow from the seed URL.
             * @default 3
             * @example 3
             */
            max_depth: number;
            /**
             * Timeout Seconds
             * @description Per-page navigation timeout in seconds.
             * @default 60
             * @example 60
             */
            timeout_seconds: number;
            /**
             * Wait For Content
             * @description Wait for dynamic content before extraction.
             * @default true
             * @example true
             */
            wait_for_content: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @description Job status progression throughout the pipeline.
         * @enum {string}
         */
        JobStatus: "pending" | "validating" | "crawling" | "extracting" | "processing" | "chunking" | "embedding" | "storing" | "completed" | "failed" | "cancelled";
        /**
         * JobStatusResponse
         * @description Current status of a scraping job.
         * @example {
         *       "chunk_count": 0,
         *       "crawl_url_count": 3,
         *       "created_at": "2024-02-09T10:00:00Z",
         *       "current_step": "crawl",
         *       "embedding_count": 0,
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "progress_pct": 25,
         *       "status": "crawling",
         *       "updated_at": "2024-02-09T10:05:00Z"
         *     }
         * @example {
         *       "chunk_count": 40,
         *       "crawl_url_count": 12,
         *       "created_at": "2024-02-09T10:00:00Z",
         *       "current_step": "done",
         *       "embedding_count": 40,
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "progress_pct": 100,
         *       "status": "completed",
         *       "updated_at": "2024-02-09T10:30:00Z"
         *     }
         * @example {
         *       "chunk_count": 0,
         *       "crawl_url_count": 1,
         *       "created_at": "2024-02-09T10:00:00Z",
         *       "current_step": "extract",
         *       "embedding_count": 0,
         *       "error_message": "Extraction timeout",
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "progress_pct": 10,
         *       "status": "failed",
         *       "updated_at": "2024-02-09T10:08:00Z"
         *     }
         * @example {
         *       "chunk_count": 0,
         *       "crawl_url_count": 0,
         *       "created_at": "2024-02-09T10:00:00Z",
         *       "current_step": "queued",
         *       "embedding_count": 0,
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "progress_pct": 0,
         *       "status": "pending",
         *       "updated_at": "2024-02-09T10:00:00Z"
         *     }
         * @example {
         *       "chunk_count": 10,
         *       "crawl_url_count": 5,
         *       "created_at": "2024-02-09T10:00:00Z",
         *       "current_step": "chunking",
         *       "embedding_count": 0,
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "progress_pct": 50,
         *       "status": "cancelled",
         *       "updated_at": "2024-02-09T10:15:00Z"
         *     }
         */
        JobStatusResponse: {
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /**
             * Crawl Url Count
             * @default 0
             */
            crawl_url_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Step */
            current_step: string;
            /**
             * Embedding Count
             * @default 0
             */
            embedding_count: number;
            /** Error Message */
            error_message?: string | null;
            /** Job Id */
            job_id: string;
            /** Progress Pct */
            progress_pct: number;
            status: components["schemas"]["JobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScrapeJobCancelResponse
         * @description Response for ``POST /jobs/{job_id}/cancel``.
         * @example {
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "new_status": "cancelled",
         *       "previous_status": "crawling"
         *     }
         * @example {
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "new_status": "cancelled",
         *       "previous_status": "pending"
         *     }
         * @example {
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "new_status": "cancelled",
         *       "previous_status": "chunking"
         *     }
         * @example {
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "new_status": "cancelled",
         *       "previous_status": "embedding"
         *     }
         * @example {
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "new_status": "cancelled",
         *       "previous_status": "validating"
         *     }
         */
        ScrapeJobCancelResponse: {
            /**
             * Job Id
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            job_id: string;
            /**
             * New Status
             * @example cancelled
             */
            new_status: string;
            /**
             * Previous Status
             * @example crawling
             */
            previous_status: string;
        };
        /**
         * ScrapeJobCreatedResponse
         * @description Response for ``POST /jobs`` when a job is enqueued.
         * @example {
         *       "created_at": "2024-02-09T10:00:00",
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "status": "pending",
         *       "url": "https://example.org/community-resources"
         *     }
         * @example {
         *       "created_at": "2024-02-09T11:00:00",
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "status": "pending",
         *       "url": "https://city.gov/housing"
         *     }
         * @example {
         *       "created_at": "2024-02-09T12:00:00",
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "status": "pending",
         *       "url": "https://health.example/clinics"
         *     }
         * @example {
         *       "created_at": "2024-02-09T13:00:00",
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "status": "pending",
         *       "url": "https://schools.example/enrollment"
         *     }
         * @example {
         *       "created_at": "2024-02-09T14:00:00",
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "status": "pending",
         *       "url": "https://transit.example/schedules"
         *     }
         */
        ScrapeJobCreatedResponse: {
            /**
             * Created At
             * @description Creation timestamp (ISO 8601).
             * @example 2024-02-09T10:00:00
             */
            created_at: string;
            /**
             * Job Id
             * @description New job UUID.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            job_id: string;
            /**
             * Modal Function Call Id
             * @description When present, the scrape worker was started with Modal ``Function.spawn``; poll ``GET /jobs/spawns/{modal_function_call_id}`` (``FunctionCall.get(timeout=0)``) per Modal job-queue docs.
             */
            modal_function_call_id?: string | null;
            /**
             * @description Initial pipeline status.
             * @example pending
             */
            status: components["schemas"]["JobStatus"];
            /**
             * Url
             * @description Seed URL for the crawl.
             * @example https://example.org/
             */
            url: string;
        };
        /**
         * ScrapeJobListItem
         * @description One row from ``GET /jobs`` (mirrors ``_JOB_DETAIL_SELECT`` serialization).
         */
        ScrapeJobListItem: {
            /**
             * Chunk Count
             * @default 0
             * @example 0
             */
            chunk_count: number;
            /** Chunking Config */
            chunking_config?: {
                [key: string]: unknown;
            } | null;
            /** Crawl Config */
            crawl_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Crawl Url Count
             * @default 0
             * @example 0
             */
            crawl_url_count: number;
            /** Created At */
            created_at?: string | null;
            /**
             * Embedding Count
             * @default 0
             * @example 0
             */
            embedding_count: number;
            /** Error Message */
            error_message?: string | null;
            /**
             * Id
             * @description Job UUID.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @example pending
             */
            status: string;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Url
             * @example https://example.org/community-resources
             */
            url: string;
            /**
             * User Id
             * @example operator-42
             */
            user_id: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ScrapeJobListResponse
         * @description Response for ``GET /jobs``.
         * @example {
         *       "jobs": [],
         *       "limit": 25,
         *       "total": 0,
         *       "user_id": "operator-42"
         *     }
         * @example {
         *       "jobs": [],
         *       "limit": 50,
         *       "total": 0
         *     }
         * @example {
         *       "jobs": [
         *         {
         *           "chunk_count": 20,
         *           "crawl_url_count": 5,
         *           "created_at": "2024-02-09T10:00:00",
         *           "embedding_count": 20,
         *           "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *           "status": "completed",
         *           "updated_at": "2024-02-09T10:20:00",
         *           "url": "https://example.org/a",
         *           "user_id": "tenant-portal-01"
         *         }
         *       ],
         *       "limit": 10,
         *       "total": 1,
         *       "user_id": "tenant-portal-01"
         *     }
         * @example {
         *       "jobs": [],
         *       "limit": 100,
         *       "total": 0,
         *       "user_id": "mobility-team"
         *     }
         * @example {
         *       "jobs": [],
         *       "limit": 1,
         *       "total": 50,
         *       "user_id": "district-batch-7"
         *     }
         */
        ScrapeJobListResponse: {
            /** Jobs */
            jobs?: components["schemas"]["ScrapeJobListItem"][];
            /**
             * Limit
             * @example 25
             */
            limit: number;
            /**
             * Total
             * @example 0
             */
            total: number;
            /**
             * User Id
             * @example operator-42
             */
            user_id?: string | null;
        };
        /**
         * ScrapeJobRequest
         * @description Request to submit a new scraping job.
         * @example {
         *       "chunking_config": {
         *         "max_size_tokens": 900,
         *         "min_size_tokens": 300
         *       },
         *       "crawl_config": {
         *         "max_depth": 2,
         *         "timeout_seconds": 90
         *       },
         *       "metadata": {
         *         "source": "schemathesis-example"
         *       },
         *       "url": "https://example.org/community-resources",
         *       "user_id": "operator-42"
         *     }
         * @example {
         *       "llm_extraction_prompt": "Extract program names and eligibility bullets.",
         *       "metadata": {
         *         "priority": "high"
         *       },
         *       "url": "https://city.gov/housing/programs",
         *       "user_id": "tenant-portal-01"
         *     }
         * @example {
         *       "chunking_config": {
         *         "overlap_ratio": 0.15,
         *         "split_by_sentence": true
         *       },
         *       "crawl_config": {
         *         "headless": true,
         *         "max_depth": 1,
         *         "timeout_seconds": 120
         *       },
         *       "url": "https://health.example/clinics/walk-in",
         *       "user_id": "operator-42"
         *     }
         * @example {
         *       "chunking_config": {
         *         "max_size_tokens": 1024,
         *         "min_size_tokens": 200
         *       },
         *       "crawl_config": {
         *         "include_images": false,
         *         "max_depth": 4
         *       },
         *       "metadata": {
         *         "run": "nightly"
         *       },
         *       "url": "https://schools.example/enrollment-2026",
         *       "user_id": "district-batch-7"
         *     }
         * @example {
         *       "crawl_config": {
         *         "include_links": true,
         *         "wait_for_content": true
         *       },
         *       "metadata": {
         *         "locale": "en"
         *       },
         *       "url": "https://transit.example/riders-guide",
         *       "user_id": "mobility-team"
         *     }
         */
        ScrapeJobRequest: {
            /** @description Optional chunking overrides for downstream embedding. */
            chunking_config?: components["schemas"]["ChunkingConfig"] | null;
            /** @description Optional crawl overrides (defaults are sensible for most sites). */
            crawl_config?: components["schemas"]["CrawlConfig"] | null;
            /**
             * Job Id
             * @description When set, the caller already inserted the ``scraping_jobs`` row (Render gateway). Used with ``MODAL_SCRAPER_PERSIST_VIA_GATEWAY`` so Modal only enqueues work.
             */
            job_id?: string | null;
            /**
             * Llm Extraction Prompt
             * @description Optional prompt guiding LLM-assisted extraction.
             */
            llm_extraction_prompt?: string | null;
            /**
             * Metadata
             * @description Arbitrary JSON metadata stored with the job.
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Url
             * Format: uri
             * @description HTTP or HTTPS seed URL for the crawl pipeline.
             */
            url: string;
            /**
             * User Id
             * @description Opaque operator or tenant id used for auditing and filtering.
             * @example operator-42
             */
            user_id: string;
        };
        /**
         * ScraperHealthResponse
         * @description JSON body for ``GET /health``.
         * @example {
         *       "service": "vecinita-scraper",
         *       "status": "ok"
         *     }
         * @example {
         *       "service": "vecinita-scraper-staging",
         *       "status": "ok"
         *     }
         * @example {
         *       "service": "vecinita-scraper",
         *       "status": "degraded"
         *     }
         * @example {
         *       "service": "vecinita-scraper-canary",
         *       "status": "ok"
         *     }
         * @example {
         *       "service": "vecinita-scraper",
         *       "status": "error"
         *     }
         */
        ScraperHealthResponse: {
            /**
             * Service
             * @description Logical service name for operators.
             * @example vecinita-scraper
             */
            service: string;
            /**
             * Status
             * @description Liveness flag.
             * @example ok
             */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScraperHealthResponse"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_scrape_spawn_result_jobs_spawns__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Modal FunctionCall object id */
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the scraping job */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the scraping job */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeJobCancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
